name: Magma AGW Build

on:
  schedule:
  - cron: "0 */6 * * *"
  push:
    branches:
    - master

jobs:
  Magma-AGW-Build:
    runs-on: macos-10.15
    steps:
    - run: echo "::set-output name=date::$(date +'%m-%d-%Y--%H-%M-%S')"
      id: date
    - uses: actions/checkout@v2
<<<<<<< HEAD
    - run: sudo ./build.sh
=======
    - run: ./build.sh
>>>>>>> d4e1891796a5a984454c9329c0511229dce0bc04
    # - uses: "marvinpinto/action-automatic-releases@latest"
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: ${{ steps.date.outputs.date }}
    #     prerelease: false
    #     files: |
    #       magma/lte/gateway/magma-packages/*.deb
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: magma-packages
    #     path: magma/lte/gateway/magma-packages/*.deb