# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
      branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: macos-10.15
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: brew install --cask docker
      - name: Check out the repo
        uses: actions/checkout@v2
      #- name: Build and Push Docker Image
       # uses: mr-smithers-excellent/docker-build-push@v4
       # with:
       #   image: motok4/private:macos-10-15
       #   registry: docker.io
       #   username: ${{ secrets.DOCKER_LOGIN }}
       #   password: ${{ secrets.DOCKER_PASS }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: motok4/private:macos-10-15
